### PR TITLE
🇳🇱 Added Dutch translation

### PR DESCRIPTION
**Pull request by roelvangils**
Dutch is my native language. I often demonstrate the Colour Contrast Analyser during accessibility workshops with a Dutch speaking audience. I think (hope) that users who have set their OS language to Dutch will appreciate the localization.

- I tried using the same terminology (where applicable) that we used in the authorized [Dutch translation of WCAG 2.1](https://www.w3.org/Translations/WCAG21-nl/#contrast-minimum).
- The only thing I didn't translate is the application name as it would sound a bit 'forced'.

I hope you might consider merging the request.

### CODE REVIEW

**Comment by roelvangils** [comment]
Hi @patrickhlauke. Any word on when the Dutch translation might be added to the app? ;) Is there anything we can do to help?

**Comment by patrickhlauke** [comment]
As I don't have merge rights on this repo anymore ... @ferllings ?

**Comment by ferllings** [comment]
> As I don't have merge rights on this repo anymore ... @ferllings ?

@patrickhlauke fixed

**Comment by patrickhlauke** [comment]
> @patrickhlauke fixed

if you mean you granted me merge rights ... not quite/yet. still says i don't have write access. (to be clear, i'm not angling for that to be honest...the above was meant more as a request for you to merge if you felt happy with the PR. i know giving merge/write access on this project may have some company/political dimension, so not too worried either way)

**Comment by roelvangils** [comment]
Thanks, @ferllings and @patrickhlauke! Is a [new release](https://github.com/ThePacielloGroup/CCAe/releases/tag/v3.1.1) (including the Dutch translation) coming soon? 😉

**Comment by ferllings** [comment]
Yes :) I need to figure out a problem with certificates first

**Comment by ferllings** [comment]
I'm sorry for the delay, I'm in the process of getting a EV Code certificate, and it takes a lot more time than I expected, to pass all the security checks

**Comment by roelvangils** [comment]
@ferllings have you been able to figure out the certificate situation? 🙂 Is there anything I can do to help?

**Comment by ferllings** [comment]
Not really. I've tried to buy one, but the validation process is overcomplicated.
I think I'll simply give up and use a standard certificate.

**Comment by roelvangils** [comment]
I have no experience with that, I'm sorry! 🙂

About the translation I added: I think someone also needs to add the new language option to the language dropdown in the Preferences pane for the app. I suppose this will not happy automatically. Is that something you can help with as well?
 
screenshot-jYyVJXrf@2x

**Comment by ferllings** [comment]
Yes, I'll take care of the rest

**Comment by roelvangils** [comment]
Without wanting to sound pushy, do you have any idea when you might be able to add the translation? :)￼

**Comment by patrickhlauke** [comment]
it's out https://github.com/ThePacielloGroup/CCAe/releases

**Comment by roelvangils** [comment]
Whoops. I didn't notice! Thanks again!

**Pull request merged**
