### PR TITLE
Translate to pt-BR

### PR DESCRIPTION
**Pull request by igorcasmarques**
- Added `pt-BR.json` to `src/views/translations` and adjusted `preferences.html` and `about.html` accordingly
- Fixed 2 typos in `en.json`
- Added comments in `preferences.html` of two variables not currently translateable (feel free to reject these as I can open issues about them)

I also noticed CopyPaste only translates the pass-fail statements; everything else stays in English. Should I open an issue about this?

### CODE REVIEW

**Review by ferllings — APPROVED** [review]

**Comment by ferllings** [comment]
@igorcasmarques could you reset the yarn.lock file?

**Comment by ferllings** [comment]
@igorcasmarques Any updates?

**Comment by igorcasmarques** [comment]
Oops, somehow I missed this. I've removed `yarn.lock` from the PR. Let me know if you need anything else.

**Comment by ferllings** [comment]
Hi @igorcasmarques I still can't merge your PR: you need to reset the file to its original state, not remove it.

**Comment by ferllings** [comment]
@igorcasmarques Sorry to push you, but I would like to release before end of week

**Comment by igorcasmarques** [comment]
Thank you for your patience, @ferllings. 

I use git for personal projects but this is my first time contributing to a public project. I hope I got this right now, but let me know if I haven't. I've squashed the commits as well to avoid clutter.

**Comment by ferllings** [comment]
@igorcasmarques All good now. Thanks for your contribution

**Pull request merged**
