### PR TITLE
Darkmode support

### PR DESCRIPTION
**Pull request by ungjinPark**
## Introduce my Dark Mode Support for Windows CCA

Hello, I'm an engineer who for testing accessibility of mobile applications and web pages. and I also have a low-visioning disability.

CCA is a good tools and I'm using it for my working always whenever testing for accessibility.

## Background
Korean copy text wasn't translated, so I translated, and then suddenly I want to implements a dark mode for this tool. So I tried, and this is that result.

## Note
I think maybe my codes are not good for team coding, and not good at other contributors to analyze, because I'm not familiar at 'electron' framework.

#### Main
image

#### About CCA
image

#### Preferences
image

#### Deficiency
image

Would you review my result codes, build, test this?

### CODE REVIEW

**Comment by ungjinPark** [comment]
re-commit for translation error of  a <label> element for Application Theme on Preferences Window

**Comment by ferllings** [comment]
Thanks for the contribution.
I'll probably fix few minor contrast issues, but it looks good.

**Comment by ferllings** [comment]
The navigation tabs font color on light mode should stay white

Light mode
Screenshot 2023-03-10 at 09 15 57

Original
Screenshot 2023-03-10 at 09 17 37

**Comment by ferllings** [comment]
Thanks for your work.
If you also sync with the current main changes, I should be able to merge pretty quickly.

Note: next time, please try to break into smaller PRs, that's easier to review.

**Comment by ferllings** [comment]
@ungjinPark Thanks. Could you check the question, about 'force-dark', and fix the tabs color?
So I can merge it.

**Comment by ungjinPark** [comment]
@ferllings  I've pushed those fixes at the 'trnaslation' branch. And, in pull request #291, there was a critical markup error. But that error fix is also included in my additional commit.

**Pull request merged**
